---
- hosts: all
  become: yes
  pre_tasks:
  - name: install git, zsh, curl, exa, tcpdump, unzip and vim
    apt:
      name:
        - git
        - zsh
        - curl
        - exa
        - tcpdump
        - unzip
        - vim
      state: present
      update_cache: yes

  roles:
    - role: gantsign.antigen
      users:

        - username: root
          antigen_libraries:
            - name: oh-my-zsh
              env:
                DISABLE_AUTO_UPDATE: '"true"'
          antigen_theme:
            name: agnoster
          antigen_bundles:
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: git
            - name: common-aliases
            - name: colored-man-pages
            - name: z
            - name: vi-mode
            - name: docker

        - username: vagrant
          antigen_libraries:
            - name: oh-my-zsh
              env:
                DISABLE_AUTO_UPDATE: '"true"'
          antigen_theme:
            name: agnoster
          antigen_bundles:
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: git
            - name: common-aliases
            - name: colored-man-pages
            - name: z
            - name: vi-mode
            - name: docker

  tasks:
    - name: add alias for exa for user root
      ansible.builtin.lineinfile:
        path: /root/.zshrc
        line: 'alias l="exa --long --header"'
        insertafter: source ~/.antigenrc
    - name: add alias for exa for user vagrant
      ansible.builtin.lineinfile:
        path: /home/vagrant/.zshrc
        line: 'alias l="exa --long --header"'
        insertafter: source ~/.antigenrc

    - name: create .vim directory for vim plug for user root
      ansible.builtin.file:
        path: /root/.vim
        state: directory
        owner: root
        group: root
        mode: 0750
        recurse: yes
    - name: create autoload directory for vim plug for user root
      ansible.builtin.file:
        path: /root/.vim/autoload
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes
    - name: create .vim directory for vim plug for user vagrant
      ansible.builtin.file:
        path: /home/vagrant/.vim
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0750
        recurse: yes
    - name: create autoload directory for vim plug for user vagrant
      ansible.builtin.file:
        path: /home/vagrant/.vim/autoload
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0755
        recurse: yes
    - name: download vim plug an place it in the right directory for user root
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /root/.vim/autoload/
        owner: root
        group: root
        mode: 0664
    - name: download vim plug an place it in the right directory for user vagrant
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/vagrant/.vim/autoload/
        owner: vagrant
        group: vagrant
        mode: 0664
    - name: copy vim config for user root
      copy:
        src: vimrc
        dest: /root/.vimrc
        owner: root
        group: root
        mode: 0640
    - name: copy vim config for user vagrant
      copy:
        src: vimrc
        dest: /home/vagrant/.vimrc
        owner: vagrant
        group: vagrant
        mode: 0640