---
- hosts: all
  become: yes
  pre_tasks:
  - name: install git, zsh, curl, exa, tcpdump, unzip and vim
    apt:
      name:
        - git
        - zsh
        - curl
        - exa
        - tcpdump
        - unzip
        - vim
      state: present
      update_cache: yes

  roles:
    - role: gantsign.antigen
      users:

        - username: root
          antigen_libraries:
            - name: oh-my-zsh
              env:
                DISABLE_AUTO_UPDATE: '"true"'
          antigen_theme:
            name: agnoster
          antigen_bundles:
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: git
            - name: common-aliases
            - name: colored-man-pages
            - name: z
            - name: vi-mode
            - name: docker

        - username: vagrant
          antigen_libraries:
            - name: oh-my-zsh
              env:
                DISABLE_AUTO_UPDATE: '"true"'
          antigen_theme:
            name: agnoster
          antigen_bundles:
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: git
            - name: common-aliases
            - name: colored-man-pages
            - name: z
            - name: vi-mode
            - name: docker

  tasks:
    - name: add alias for exa for user root
      blockinfile:
        path: "{{ item.path }}"
        block: |
          alias l="exa --long --header"
          alias ls="exa --long --header"
          alias la="exa --long --header --all"
      loop:
        - { path: '/root/.zshrc' }
        - { path: '/home/vagrant/.zshrc' }

    - name: ansible create directory's for vim
      file:
        path: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        recurse: yes   
        state: directory
      loop:
        - { dest: '/root/.vim', mode: '0750', owner: 'root', group: 'root' }
        - { dest: '/root/.vim/autoload', mode: '0755', owner: 'root', group: 'root' }
        - { dest: '/home/vagrant/.vim', mode: '0750', owner: 'vagrant', group: 'vagrant' }
        - { dest: '/home/vagrant/.vim/autoload', mode: '0755', owner: 'vagrant', group: 'vagrant' }

    - name: download vim plug an place it in the right directory
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: 0664
      loop:
        - { dest: '/root/.vim/autoload/', owner: 'root', group: 'root' }
        - { dest: '/home/vagrant/.vim/autoload/', owner: 'vagrant', group: 'vagrant' }

    - name: copy vim config in the right directory
      copy:
        src: vimrc
        dest: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: 0640
      loop:
        - { dest: '/root/.vimrc', owner: 'root', group: 'root' }
        - { dest: '/home/vagrant/.vimrc', owner: 'vagrant', group: 'vagrant' }

    - name: install vim plugins
      command: vim +'PlugInstall --sync' +qall &> /dev/null
      become: yes
      become_user: "{{ item.user }}"
      loop:
        - { user: 'root' }
        - { user: 'vagrant' }